basic:
  map_frame: "map"                            # publish frame
  loop_update_hz: 2.0                         # Loop detection Hz
  vis_hz: 1.0                                 # visualize Hz
  vis_pcd_voxel_resolution: 0.2

keyframe:
  keyframe_threshold: 1.5                     # unit [meter] every this distance, generate keyframe
  subkeyframes_number: 5                      # how many subkeyframes are merged to ICP with current keyframe (closest-this ~ closest+this, if exists)

loop:
  loop_detection_radius: 35.0                 # unit [meter] within this radius, check if loop or not
  loop_detection_timediff_threshold: 30.0     # unit [sec] check if two keyframes are loop if times are farther than this

quatro_nano_gicp_voxel_resolution: 0.3

nano_gicp:
  thread_number: 0                            # if 0, max number of core
  icp_score_threshold: 1.0                    # lower is more accurate, for loop detection
  correspondences_number: 15
  max_iter: 32
  transformation_epsilon: 0.01
  euclidean_fitness_epsilon: 0.01
  ransac:
    max_iter: 5
    outlier_rejection_threshold: 1.0

quatro:
  fpfh_normal_radius: 0.02
  fpfh_radius: 0.04
  estimating_scale: false
  noise_bound: 0.25
  rotation:
    gnc_factor: 1.39
    rot_cost_diff_threshold: 0.0001
    num_max_iter: 50